apiVersion: v1
kind: ServiceAccount
metadata:
  name: ace-tekton-service-account
imagePullSecrets:
  - name: regcred
  # Needed for cp.icr.io if using the "ace" image 
  # but not needed for ace-minimal
  #- name: ibm-entitlement-key
secrets:
  - name: regcred
  # Needed for cp.icr.io if using the "ace" image 
  # but not needed for ace-minimal
  #- name: ibm-entitlement-key
---

kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: pipeline-role
rules:
- apiGroups: ["extensions", "apps", "appconnect.ibm.com", "", "v1"]
  resources: ["services", "deployments", "pods", "integrationservers", "pods/exec", "integrationruntimes"]
  verbs: ["get", "create", "update", "patch", "list", "delete", "exec", "watch"]

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pipeline-role-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: pipeline-role
subjects:
- kind: ServiceAccount
  name: ace-tekton-service-account

---
# Needed for OpenShift registry pushes
# Note that the project for the container must match the namespace for the Tekton pipeline
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: system-image-builder-role-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: 'system:image-builder'
subjects:
- kind: ServiceAccount
  name: ace-tekton-service-account