kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: tea-route
spec:
  # Adjust for namespace (replace ace) and cluster name (replace openshift.mycompany.com)
  host: tea-route-ace.apps.openshift.mycompany.com
  to:
    kind: Service
    name: tea-tekton-service
    weight: 100
  port:
    targetPort: 7800
  wildcardPolicy: None
