kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: tea-route
  namespace: default
spec:
  host: tea-route-default.apps.openshift-20230428.dolbyfamily.org
  to:
    kind: Service
    name: tea-tekton-service
    weight: 100
  port:
    targetPort: 7800
  wildcardPolicy: None
