---
apiVersion: v1
kind: Pod
metadata:
  name: db2-test-pod
  labels:
    app: db2-test-pod
spec:
  restartPolicy: Never
  containers:
    - name: db2-test-container
      env:
        - name: LICENSE
          value: accept
        - name: DBNAME
          value: TESTDB
        - name: DB2INST1_PASSWORD
          value: PASSWORD_REPLACEMENT_STRING
      securityContext:
        privileged: true
      imagePullPolicy: Always
      image: icr.io/db2_community/db2