apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: ace-minimal-build-image-build-and-push
spec:
  # The security and environment settings are needed for OpenShift in a non-default
  # namespace such as cp4i. Kaniko is expecting to be root in the container.
  stepTemplate:
    securityContext:
      runAsUser: 0
    env:
      - name: "HOME"
        value: "/tekton/home"
  params:
    - name: dockerRegistry
      type: string
    - name: url
      type: string
    - name: revision
      type: string
    - name: buildImage
      type: string
    - name: runtimeImage
      type: string
  steps:
    - name: clone
      image: gcr.io/tekton-releases/github.com/tektoncd/pipeline/cmd/git-init:v0.18.1
      script: |
        #!/bin/sh
        cd /work
        git clone -b $(params.revision) $(params.url)
      volumeMounts:
        - mountPath: /work
          name: work
    - name: ace-minimal-build-push
      image: gcr.io/kaniko-project/executor:latest
      # specifying DOCKER_CONFIG is required to allow kaniko to detect docker credential
      env:
        - name: "DOCKER_CONFIG"
          value: "/tekton/home/.docker/"
      command:
        - /kaniko/executor
      args:
        - --dockerfile=/work/ace-demo-pipeline/demo-infrastructure/docker/ace-minimal-build/Dockerfile
        - --destination=$(params.dockerRegistry)/$(params.buildImage)
        - --context=/work/ace-demo-pipeline/demo-infrastructure/docker/ace-minimal-build
        - --build-arg=BASE_IMAGE=$(params.dockerRegistry)/$(params.runtimeImage)
        - --skip-tls-verify
      volumeMounts:
        - mountPath: /work
          name: work
  volumes:
    - name: work
      emptyDir: {}
