apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: ace-minimal-image-pipeline-run-1
spec:
  serviceAccountName: ace-tekton-service-account
  pipelineRef:
    name: ace-minimal-image-pipeline
  params:
    - name: dockerRegistry
      value: "us.icr.io/ace-containers"
    - name: aceDownloadUrl
      value: "https://iwm.dhe.ibm.com/sdfdl/v2/regs2/mbford/Xa.2/Xb.WJL1CuPI9gANEhP8GuPD_qX1rj6x5R4yTUM7s_C2ue8/Xc.12.0.7.0-ACE-LINUX64-DEVELOPER.tar.gz/Xd./Xf.lPr.D1vk/Xg.12164875/Xi.swg-wmbfd/XY.regsrvs/XZ.pPVETUejcqPsVfDVKbdNu6IRpo4TkykU/12.0.7.0-ACE-LINUX64-DEVELOPER.tar.gz"
