apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: ace-pipeline
spec:
  params:
    - name: dockerRegistry
      type: string
    - name: url
      type: string
      default: "https://github.com/ot4i/ace-demo-pipeline"
    - name: revision
      type: string
      default: "main"
    - name: buildImage
      type: string
      default: "ace-minimal-build:12.0.10.0-alpine"
    - name: runtimeImage
      type: string
      default: "ace-minimal:12.0.10.0-alpine"
  tasks:
    - name: build-from-source
      taskRef:
        name: maven-ace-build
      params:
        - name: dockerRegistry
          value: $(params.dockerRegistry)
        - name: url
          value: $(params.url)
        - name: revision
          value: $(params.revision)
        - name: buildImage
          value: $(params.buildImage)
        - name: runtimeImage
          value: $(params.runtimeImage)
    - name: deploy-to-cluster
      taskRef:
        name: deploy-to-cluster
      params:
        - name: dockerRegistry
          value: $(params.dockerRegistry)
        - name: url
          value: $(params.url)
        - name: revision
          value: $(params.revision)
      runAfter:
        - build-from-source
