apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: ace-pipeline
spec:
  params:
    - name: outputRegistry
      type: string
    - name: url
      type: string
      default: "https://github.com/ot4i/ace-demo-pipeline"
    - name: revision
      type: string
      default: "main"
    - name: buildImage
      type: string
    - name: runtimeBaseImage
      type: string
  tasks:
    - name: build-from-source
      taskRef:
        name: maven-ace-build
      params:
        - name: outputRegistry
          value: $(params.outputRegistry)
        - name: url
          value: $(params.url)
        - name: revision
          value: $(params.revision)
        - name: buildImage
          value: $(params.buildImage)
        - name: runtimeBaseImage
          value: $(params.runtimeBaseImage)
    - name: deploy-to-cluster
      taskRef:
        name: deploy-to-cluster
      params:
        - name: dockerRegistry
          value: $(params.outputRegistry)
        - name: url
          value: $(params.url)
        - name: revision
          value: $(params.revision)
      runAfter:
        - build-from-source
