apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: ace-pipeline-run-1
spec:
  serviceAccountName: ace-tekton-service-account
  pipelineRef:
    name: ace-pipeline
  params:
    - name: outputRegistry
      # OpenShift
      #value: "image-registry.openshift-image-registry.svc.cluster.local:5000/default"
      #value: "quay.io/trevor_dolby"
      #value: "us.icr.io/ace-containers"
      #value: "aceDemoRegistry.azurecr.io"
      # Minikube
      value: "192.168.49.2:5000/default"
    - name: buildImage
      # Requires an IBM Entitlement Key
      #value: "cp.icr.io/cp/appc/ace:12.0.11.0-r1"
      # ace-minimal can be built from the ACE package without needing a key
      #value: "image-registry.openshift-image-registry.svc.cluster.local:5000/default/ace-minimal:12.0.11.0-alpine"
      # Need to use the -build image for Maven
      #value: "image-registry.openshift-image-registry.svc.cluster.local:5000/default/ace-minimal-build:12.0.11.0-alpine"
      value: "192.168.49.2:5000/default/ace-minimal-build:12.0.11.0-alpine"
    - name: runtimeBaseImage
      # Requires an IBM Entitlement Key
      #value: "cp.icr.io/cp/appc/ace:12.0.11.0-r1"
      # ace-minimal can be built from the ACE package without needing a key
      # value: "image-registry.openshift-image-registry.svc.cluster.local:5000/default/ace-minimal:12.0.11.0-alpine"
      # Minikube
      value: "192.168.49.2:5000/default/ace-minimal:12.0.11.0-alpine"
    - name: url
      value: "https://github.com/trevor-dolby-at-ibm-com/ace-demo-pipeline"
    - name: revision
      value: "os-4.14"
    #- name: knativeDeploy
    #  value: "true"
