apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  # Can use generated names with kubectl create; follow logs with "tkn pipeline logs ace-pipeline -f" to
  # avoid needing a fixed name.
  #generateName: ace-pipeline-run-

  # Fixed name allows "tkn pr delete ace-pipeline-run-1 -f ; kubectl apply -f tekton/ace-pipeline-run.yaml ; tkn pr logs ace-pipeline-run-1 -f"
  # which has a slightly nicer log format.
  name: ace-pipeline-run-1
spec:
  serviceAccountName: ace-tekton-service-account
  pipelineRef:
    name: ace-pipeline
  params:
    - name: outputRegistry
      # OpenShift
      #value: "image-registry.openshift-image-registry.svc.cluster.local:5000/default"
      #value: "quay.io/trevor_dolby"
      #value: "us.icr.io/ace-containers"
      #value: "aceDemoRegistry.azurecr.io"
      # Minikube
      value: "192.168.49.2:5000/default"
    - name: buildImage
      # Requires an IBM Entitlement Key
      #value: "cp.icr.io/cp/appc/ace:12.0.11.0-r1"
      # ace-minimal can be built from the ACE package without needing a key
      #value: "image-registry.openshift-image-registry.svc.cluster.local:5000/default/ace-minimal:12.0.11.0-alpine"
      # Need to use the -build image for Maven
      #value: "image-registry.openshift-image-registry.svc.cluster.local:5000/default/ace-minimal-build:12.0.11.0-alpine"
      value: "192.168.49.2:5000/default/ace-minimal-build:12.0.11.0-alpine"
    - name: runtimeBaseImage
      # Requires an IBM Entitlement Key
      #value: "cp.icr.io/cp/appc/ace:12.0.11.0-r1"
      # ace-minimal can be built from the ACE package without needing a key
      # value: "image-registry.openshift-image-registry.svc.cluster.local:5000/default/ace-minimal:12.0.11.0-alpine"
      # Minikube
      value: "192.168.49.2:5000/default/ace-minimal:12.0.11.0-alpine"
      # Local copy of ace container
      #value: "192.168.49.2:5000/default/ace:12.0.11.0-r1"
    - name: url
      value: "https://github.com/ot4i/ace-demo-pipeline"
    - name: revision
      value: "main"
    #- name: knativeDeploy
    #  value: "true"
