apiVersion: v1
kind: Pod
metadata:
  name: force-pull
spec:
  containers:
  - name: force-pull-base
    imagePullPolicy: Always
    image: image-registry.openshift-image-registry.svc.cluster.local:5000/default/ace-minimal:12.0.8.0-alpine
    command: ["sleep"]
    args: ["10"]
  - name: force-pull-build
    imagePullPolicy: Always
    image: image-registry.openshift-image-registry.svc.cluster.local:5000/default/ace-minimal-build:12.0.8.0-alpine
    command: ["sleep"]
    args: ["10"]
  restartPolicy: Never
