apiVersion: tekton.dev/v1beta1
kind: TaskRun
metadata:
  name: knative-deploy-taskrun-1
spec:
  serviceAccountName: ace-tekton-service-account
  taskRef:
    name: knative-deploy
  params:
    - name: dockerRegistry
      value: "image-registry.openshift-image-registry.svc.cluster.local:5000/ace"
    - name: url
      value: "https://github.com/trevor-dolby-at-ibm-com/ace-demo-pipeline"
    - name: revision
      value: "main"
