apiVersion: apps/v1
kind: Deployment
metadata:
  name: tea-tekton
spec:
  selector:
    matchLabels:
      app: tea-tekton
  replicas: 1
  template:
    metadata:
      labels:
        app: tea-tekton
      annotations:
        productName: "IBM App Connect Enterprise for non-production"
        productID: eb5b5e73f62b4dcf8c434c6274a158a7
        productMetric: FREE
    spec:
      volumes:
      - name: secret-volume-2
        secret:
          secretName: jdbc-secret
      # This is now handled via the "default" service account
      # kubectl patch serviceaccount default --type=json -p='[{"op": "add", "path": "/imagePullSecrets/-", "value": {"name": "regcred"}}]'
      #imagePullSecrets:
      #- name: regcred
      containers:
      - name: tea-tekton
        image: DOCKER_REGISTRY/tea-tekton:IMAGE_TAG
        ports:
        - containerPort: 7800
        imagePullPolicy: Always
        volumeMounts:
        - name: secret-volume-2
          mountPath: /var/run/secrets/jdbc
