apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: knative-role-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: knative-serving-admin
subjects:
- kind: ServiceAccount
  name: ace-tekton-service-account
  namespace: default
