apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: cp4i-pipeline-run-
  namespace: cp4i
spec:
  serviceAccountName: cp4i-tekton-service-account
  pipelineRef:
    name: cp4i-pipeline
  params:
    - name: dockerRegistry
      value: "image-registry.openshift-image-registry.svc.cluster.local:5000/cp4i"
      # Minikube
      #value: "192.168.49.2:5000/default"
    - name: appName
      value: "tea-tekton-cp4i"
    - name: url
      value: "https://github.com/ot4i/ace-demo-pipeline"
    - name: revision
      value: "main"
    - name: buildImage
      value: "cp.icr.io/cp/appc/ace:13.0.4.0-r1"
      # For Maven builds - build ace-minimal-build first
      #value: "image-registry.openshift-image-registry.svc.cluster.local:5000/cp4i/ace-minimal-build:13.0.4.0-alpine"
    - name: runtimeBaseImage
      value: "cp.icr.io/cp/appc/ace-server-prod:13.0.4.0-r1-20250621-111331"
      # If shadowed locally
      #value: "image-registry.openshift-image-registry.svc.cluster.local:5000/cp4i/ace-server-prod:13.0.4.0-r1-20250621-111331"
