apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: cp4i-pipeline-run-1
  namespace: cp4i
spec:
  serviceAccountName: cp4i-tekton-service-account
  pipelineRef:
    name: cp4i-pipeline
  params:
    - name: dockerRegistry
      value: "image-registry.openshift-image-registry.svc.cluster.local:5000/default"
    - name: url
      value: "https://github.com/trevor-dolby-at-ibm-com/ace-demo-pipeline"
    - name: revision
      value: "os-4.14"