apiVersion: appconnect.ibm.com/v1beta1
kind: IntegrationServer
metadata:
  name: tea-tekton-cp4i-ct
  namespace: cp4i
spec:
  license:
    accept: true
    license: L-APEH-CCHL5W
    use: AppConnectEnterpriseNonProductionFREE
  pod:
    containers:
      runtime:
        image: >-
          DOCKER_REGISTRY/tea-tekton-cp4i-ct:latest
        livenessProbe:
          failureThreshold: 1000000
        resources:
          limits:
            cpu: 300m
            memory: 368Mi
          requests:
            cpu: 300m
            memory: 368Mi
  adminServerSecure: true
  env:  
    - name: MQSI_PREVENT_CONTAINER_SHUTDOWN
      value: 'true'
  createDashboardUsers: true
  replicas: 1
  configurations:
    - teajdbc-policy
    - default-policy
    - teajdbc
  version: '12.0.5.0-r2'
