apiVersion: appconnect.ibm.com/v1beta1
kind: IntegrationServer
metadata:
  name: tea-tekton-cp4i
  namespace: cp4i
spec:
  license:
    accept: true
    license: L-APEH-CCHL5W
    use: AppConnectEnterpriseNonProductionFREE
  pod:
    containers:
      runtime:
        image: >-
          DOCKER_REGISTRY/tea-tekton-cp4i:latest
        resources:
          limits:
            cpu: 300m
            memory: 368Mi
          requests:
            cpu: 300m
            memory: 368Mi
  adminServerSecure: true
  createDashboardUsers: true
  replicas: 1
  version: '12.0.5.0-r2'
