apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: ace-minimal-build-image-pipeline-run-1
spec:
  serviceAccountName: ace-tekton-service-account
  pipelineRef:
    name: ace-minimal-build-image-pipeline
  params:
    - name: dockerRegistry
      value: "image-registry.openshift-image-registry.svc.cluster.local:5000/default"
#    - name: buildImage
#      value: "ace-minimal-build:12.0.10.0-alpine-java11"
#    - name: runtimeImage
#      value: "ace-minimal:12.0.10.0-alpine-java11"
