apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: ace-minimal-image-pipeline-run-1
spec:
  serviceAccountName: ace-tekton-service-account
  pipelineRef:
    name: ace-minimal-image-pipeline
  params:
    - name: dockerRegistry
      value: "image-registry.openshift-image-registry.svc.cluster.local:5000/default"
    - name: aceDownloadUrl
      value: "http://192.168.1.70:49177/ace/12.0.10.0-ACE-LINUX64-DEVELOPER.tar.gz"
