apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: ace-minimal-build-image-pipeline-run-1
spec:
  serviceAccountName: cp4i-tekton-service-account
  #serviceAccountName: ace-tekton-service-account
  pipelineRef:
    name: ace-minimal-build-image-pipeline
  params:
    - name: dockerRegistry
      value: "image-registry.openshift-image-registry.svc.cluster.local:5000/default"
    - name: aceDownloadUrl
      #value: "http://192.168.1.70:49177/ace/12.0.11.0-ACE-LINUX64-DEVELOPER.tar.gz"
      value: "https://iwm.dhe.ibm.com/sdfdl/v2/regs2/mbford/Xa.2/Xb.WJL1CuPI9omKj5inyv9-ir8PMDDUU8v2iYo-Oc5KPVI/Xc.12.0.11.0-ACE-LINUX64-DEVELOPER.tar.gz/Xd./Xf.lPr.D1vk/Xg.12260000/Xi.swg-wmbfd/XY.regsrvs/XZ._4mLAwxEK3xwdP7B6oAhifJgsNyp-ePc/12.0.11.0-ACE-LINUX64-DEVELOPER.tar.gz"
#    - name: buildImage
#      value: "ace-minimal-build:12.0.10.0-alpine-java11"
#    - name: runtimeImage
#      value: "ace-minimal:12.0.10.0-alpine-java11"
#    - name: aceDockerFile
#      value: "experimental/ace-minimal/Dockerfile.alpine-java11"
