apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: aceaas-pipeline-run-
  # Fixed name allows "tkn pr delete aceaas-pipeline-run-1 -f ; kubectl apply -f tekton/aceaas/aceaas-pipeline-run.yaml ; tkn pr logs aceaas-pipeline-run-1 -f"
  #name: aceaas-pipeline-run-1
spec:
  serviceAccountName: ace-tekton-service-account
  pipelineRef:
    name: aceaas-pipeline
  params:
    - name: buildImage
      # Requires an IBM Entitlement Key
      value: "cp.icr.io/cp/appc/ace:12.0.11.0-r1"
      # ace-minimal does not have curl, so we need to use the -build image for curl
      #value: "image-registry.openshift-image-registry.svc.cluster.local:5000/default/ace-minimal-build:12.0.11.0-alpine"
    - name: url
      value: "https://github.com/ot4i/ace-demo-pipeline"
    - name: revision
      value: "main"
    - name: deployPrefix
      value: "tdolby"
    - name: createConfiguration
      value: "true"
    - name: appConEndpoint
      # US East default    
      value: "api.p-vir-c1.appconnect.automation.ibm.com"
