apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: aceaas-pipeline-run-1
spec:
  serviceAccountName: ace-tekton-service-account
  pipelineRef:
    name: aceaas-pipeline
  params:
    - name: buildImage
      # Requires an IBM Entitlement Key
      #value: "cp.icr.io/cp/appc/ace:12.0.11.0-r1"
      # ace-minimal does not have curl, so we need to use the -build image for curl
      value: "image-registry.openshift-image-registry.svc.cluster.local:5000/default/ace-minimal-build:12.0.11.0-alpine"
    - name: url
      value: "https://github.com/trevor-dolby-at-ibm-com/ace-demo-pipeline"
    - name: revision
      value: "os-4.14"
    - name: deployPrefix
      value: "tdolby"
