name: Docker Image

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      - name: Build the Docker image
        run: |
          mkdir -p /tmp/build/ace-server
          touch /tmp/build/ace-server/dummy-file
          cp tekton/Dockerfile /tmp/build/Dockerfile
          cd /tmp/build
          docker build . --file Dockerfile --build-arg BASE_IMAGE=tdolby/experimental:ace-minimal-12.0.7.0-alpine tdolby/experimental:tea-github-action-latest
