# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a set of commands using the runners shell
      - name: Download ACE
        run: |
          /bin/pwd
          #env | sort
          #df -k
          curl -so moby-download-frozen-image-v2.sh https://raw.githubusercontent.com/moby/moby/master/contrib/download-frozen-image-v2.sh
          mkdir ace-minimal-download
          bash moby-download-frozen-image-v2.sh ace-minimal-download tdolby/experimental:ace-minimal-12.0.1.0-alpine
          mkdir ace-minimal-image-unzip
          grep layer.tar ace-minimal-download/manifest.json | tr -d '"' | tr -d ',' | xargs -n 1 tar -C ace-minimal-image-unzip -xf
          #curl -s http://public.dhe.ibm.com/ibmdl/export/pub/software/websphere/integration/12.0.1.0-ACE-LINUX64-DEVELOPER.tar.gz | tar -xzf -
          #ace-12.0.1.0/ace accept license silently
          #. ace-12.0.1.0/server/bin/mqsiprofile
          export LICENSE=accept
          . ace-minimal-image-unzip/opt/ibm/ace-11/server/bin/mqsiprofile
          export MQSI_REGISTRY=$PWD/ace-minimal-image-unzip/var/mqsi
          mqsilist
          
      # Runs a set of commands using the runners shell
      - name: Build ACE projects
        run: |
          #. ace-12.0.1.0/server/bin/mqsiprofile
          export LICENSE=accept
          . ace-minimal-image-unzip/opt/ibm/ace-11/server/bin/mqsiprofile
          export MQSI_REGISTRY=$PWD/ace-minimal-image-unzip/var/mqsi
          mqsilist
          echo "Running Maven install to $PWD/ace-server . . ."
          mvn --no-transfer-progress -Dinstall.work.directory=$PWD/ace-server install
