# CI build to validate PR changes before merging

name: cp

permissions:
  id-token: write
  contents: read
  
# Controls when the action will run. 
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container: 
      image: ibmcom/ace:latest
      options: --user 0   # 👈 fuerza a correr como root
    steps:
      - uses: actions/checkout@v5
      
      - name: Build the application and test it
        shell: bash
        run: |
          echo "Loading ACE profile"
          export LICENSE=accept
          set +e 
          . /opt/ibm/ace-13/server/bin/mqsiprofile
          set -e 

          echo ========================================================================
          echo Building application
          echo ========================================================================
          ibmint package --input-path . --output-bar-file $PWD/tea-application-combined.bar \
            --project TeaSharedLibraryJava --project TeaSharedLibrary \
            --project TeaRESTApplication --project TeaCallableApplicationV2 \
            --compile-maps-and-schemas 

          echo ========================================================================
          echo Building unit tests
          echo ========================================================================
          mqsicreateworkdir /tmp/test-work-dir
          mqsibar -w /tmp/test-work-dir -a $PWD/tea-application-combined.bar 
          ibmint deploy --input-path . --output-work-directory /tmp/test-work-dir \
            --project TeaRESTApplication_UnitTest

          echo ========================================================================
          echo Running unit tests
          echo ========================================================================
          IntegrationServer -w /tmp/test-work-dir --no-nodejs --start-msgflows false \
            --test-project TeaRESTApplication_UnitTest
