# CI build to validate PR changes before merging

name: CI

# Controls when the action will run. 
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    container: tdolby/experimental:ace-minimal-build-12.0.7.0-alpine
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      - name: Build the application
        run: |
          rm -rf /tmp/build
          mkdir -p /tmp/build
          bash -c ". /etc/profile.d/profile-with-product-java-paths.sh && mvn --no-transfer-progress -Dinstall.work.directory=/tmp/build/ace-server install"
