# CI build to validate PR changes before merging

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    container: 
      image: tdolby/experimental:ace-minimal-build-12.0.7.0-alpine
      options: -u 0
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      
      - name: Install gradle
        run: |
          unset LD_LIBRARY_PATH || /bin/true
          apk add gradle
          
      - name: Build the application and test it
        run: |
          echo "Running Gradle build and unit test"
          bash -c ". /etc/profile.d/profile-with-product-java-paths.sh && gradle -PCLASSPATH=$CLASSPATH"
